# Generated by Django 4.2 on 2023-08-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='static/images/')),
                ('publishedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
