# Generated by Django 4.2 on 2023-08-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newss', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Newss',
        ),
    ]
