# Generated by Django 4.2 on 2023-08-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newss', '0002_rename_news_newss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newss',
            new_name='News',
        ),
    ]
