# Generated by Django 4.2 on 2023-08-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newss', '0003_rename_newss_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
