# Generated by Django 4.2 on 2023-08-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newss', '0004_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
