# Generated by Django 4.2 on 2023-08-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newss', '0005_alter_news_options_news_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(),
        ),
    ]
