# Generated by Django 4.2 on 2023-08-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newss', '0012_alter_comments_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='article_url',
            field=models.URLField(null=True),
        ),
    ]
